---
- name: Deploy .zshrc to user's home
  ansible.builtin.template:
    src: .zshrc.j2
    dest: "~/.zshrc"
    owner: "{{ user }}"
    mode: "0644"
  become: true
  become_user: "{{ user }}"

- name: Add pacman hook to update zsh completions
  ansible.builtin.copy:
    src: zsh-rehash.hook
    dest: "/etc/pacman.d/hooks/zsh-rehash.hook"
    owner: root
    mode: "0644"
  become: true
  become_user: root
  when: package_manager == "pacman"

- name: Set zsh as the default shell for the user
  ansible.builtin.user:
    name: "{{ user }}"
    shell: /usr/bin/zsh
  become: true
  become_user: root
  when: shell == "zsh"

- name: Install Oh My Posh if not present
  ansible.builtin.shell: |
    if [ ! -f "/home/{{ user }}/.local/bin/oh-my-posh" ]; then
      set -o pipefail
      curl -s https://ohmyposh.dev/install.sh | bash -s -- -d /home/{{ user }}/.local/bin/
      if [ $? -eq 0 ]; then
        echo "changed=True comment='Oh My Posh installed successfully.'"
      else
        echo "failed=True comment='Installation failed.'"
        exit 1
      fi
    else
      echo "changed=False comment='Oh My Posh is already installed.'"
    fi
  register: oh_my_posh_installation
  become: true
  become_user: "{{ user }}"
  when: oh_my_posh | bool
  changed_when: "'changed=True' in oh_my_posh_installation.stdout"
  failed_when: "'failed=True' in oh_my_posh_installation.stdout"
  check_mode: false

- name: Create Oh My Posh themes directory
  ansible.builtin.file:
    path: "/home/{{ user }}/.config/oh-my-posh/themes"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0755"
  become: true
  when: oh_my_posh | bool

- name: Copy Oh My Posh theme file to themes directory
  ansible.builtin.copy:
    src: "infinite.omp.json"
    dest: "/home/{{ user }}/.config/oh-my-posh/themes/infinite.omp.json"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  become: true
  when: oh_my_posh | bool
