---
- name: Restart sshd
  ansible.builtin.service:
    name: "sshd"
    state: restarted
  when: "'sshd.service' in ansible_facts.services and ansible_facts.services['sshd.service'].state == 'running'"
  become: true
